version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    expose:
      - '5432'
    env_file: ./postgres.env
    volumes:
      - ./postgres_scripts:/docker-entrypoint-initdb.d/
  backend:
    build:
      context: ./backend
      target: production
    image: backend:production
    ports:
      - '3000:3000'
    env_file: ./backend.env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      target: production
    image: frontend:production
    ports: 
      - '8080:8080'
      - '8081:80'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

