version: '3.4'

services:
  backend:
    build:
      context: ./backend
      target: production
    image: backend:production
    ports:
      - '3000:3000'
    env_file: backend.env
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      target: production
    image: frontend:production
    ports: 
      - '80:80'
    depends_on:
      - backend

